version: "3.4"
services:

  flask-teaser:
    build:
      dockerfile: .docker/Dockerfile
      context: ../
    environment:
      - FLASK_APP=app.py
      - TEASER_CAR_PORT=IN_MEMORY
    ports:
      - "5000:5000"